Lab4/Lab3new/Models/PhoneContext.cs
using System.Data.Entity;


namespace Lab3new.Models
{
    public class PhoneContext: DbContext
    {
        public PhoneContext() : base("DBConnection") { }
        public DbSet<Telephone> Telephone { get; set; }
    }
}

Lab4/Lab3new/Models/Telephone.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Lab3new.Models
{
    public class Telephone
    {
        public int id { get; set; }
        public string surname { get; set; }
        public string number { get; set; }
    }
}

Lab4/Lab3new/Controllers/DictController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Lab3new.Models;

namespace Lab3new.Controllers
{
    public class DictController : Controller
    {
        PhoneContext db = new PhoneContext();

        public ActionResult Index()
        {
            return View(db.Telephone);
        }

        public ActionResult Add()
        {
            return View(db.Telephone);
        }

        [HttpPost]
        public ActionResult Add(string surname, string number)
        {
            if (surname == null && number == null)
            {
                return HttpNotFound();
            }

            Telephone tel = new Telephone();
            tel.number = number;
            tel.surname = surname;

            db.Telephone.Add(tel);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

        public ActionResult Update()
        {
            return View(db.Telephone);
        }

        [HttpPost]
        public ActionResult Update(int? id, string surname, string number)
        {
            if (id == null && surname == null && number == null)
            {
                return HttpNotFound();
            }

            Telephone tel = db.Telephone.Find(id);
            if (tel != null)
            {
                tel.surname = surname;
                tel.number = number;
                db.Entry(tel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return HttpNotFound();
        }

        public ActionResult Delete()
        {
            return View(db.Telephone);
        }

        [HttpPost]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }


            Telephone tel = db.Telephone.Find(id);
            if (tel != null)
            {
                db.Telephone.Remove(tel);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

Lab4/Lab3new/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lab3new.Controllers
{
    public class ErrorController : Controller
    {
        // GET: Error
        public ActionResult NotFound()
        {
            string uri = Request.Url.ToString().Split(';')[1];
            string method = Request.HttpMethod;
            Response.StatusCode = 404;
            ViewBag.uri = uri;
            ViewBag.method = method;
            return View();
        }
    }
}

Lab4/Lab3new/Views/Dict/Add.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="jumbotron">
        <h3>Add</h3>
        @using (Html.BeginForm("Add", "Dict", FormMethod.Post))
        {
            <div>
                <p>Surname: <input type="text" id="surname" name="surname" /></p>
                <p>Number: <input type="number" id="number" name="number" min="0" max="999999999"></p>
                <p><input type="submit"></p>
            </div>
        }
    </div>
</body>
</html>

Lab4/Lab3new/Views/Dict/Delete.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="jumbotron">
        <h3>Delete</h3>
        @using (Html.BeginForm("Delete", "Dict", FormMethod.Post))
        {
            <div>
                <p>Enter id:<input type="number" id="id" name="id" min="1"></p>
                <p><input type="submit"></p>
            </div>
        }
    </div>
</body>
</html>

Lab4/Lab3new/Views/Dict/Index.cshtml
@using Lab3new.Models
@{
    Layout = null;
}
@model IEnumerable<Telephone>

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    @Styles.Render("~/Content/css")

</head>
<body>
    <div class="jumbotron" style="width:100%; display:flex; flex-direction: column; justify-content: center;">
        <table border="1" style="margin: 0 20% 0 20%; width:60%; text-align: center;">
            <thead>
                <tr>
                    <th style="text-align: center">Id</th>
                    <th style="text-align: center">Surnames</th>
                    <th style="text-align: center">Telephone Numbers</th>
                </tr>
            </thead>
            <tbody style="overflow-y: auto; overflow-x: hidden; height: 85%;">
                @foreach (Telephone telephone in Model)
                {
                    <tr>
                        <td>@telephone.id</td>
                        <td>@telephone.surname</td>
                        <td>@telephone.number</td>
                    </tr>
                }
            </tbody>
        </table>
        <div style="margin: 0 35% 0 35%; display:flex;flex-direction: row; justify-content: space-between; width: 30%">
            <span style="margin: 50px 0px 50px 0px">@Html.ActionLink("Add", "Add")</span>
            <span style="margin: 50px 0px 50px 0px">@Html.ActionLink("Update", "Update")</span>
            <span style="margin: 50px 0px 50px 0px">@Html.ActionLink("Delete", "Delete")</span>
        </div>
    </div>
</body>
</html>

Lab4/Lab3new/Views/Dict/Update.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Update</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="jumbotron">
        <h3>Update</h3>
        @using (Html.BeginForm("Update", "Dict", FormMethod.Post))
        {
            <div>
                <p>Id:      <input type="number" id="id" name="id" min="0" width="200"></p>
                <p>Surname: <input type="text" id="surname" name="surname" width="230" /></p>
                <p>Number:  <input type="number" id="number" name="number" min="0" max="999999999" width="300"></p>
                <p><input type="submit"></p>
            </div>
        }
    </div>
</body>
</html>

Lab4/Lab3new/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>